/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.managment;

/**
 *
 * @author Isuranji Thamosha
 */
public class generate_bill extends javax.swing.JFrame {

    /**
     * Creates new form generate_bill
     */
    public generate_bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfbill_discount = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jfd_icharge = new javax.swing.JLabel();
        jfm_charge = new javax.swing.JLabel();
        jfr_charge = new javax.swing.JLabel();
        jfs_charge = new javax.swing.JLabel();
        jfd_qualification = new javax.swing.JLabel();
        jft_charge = new javax.swing.JLabel();
        tfd_charge = new javax.swing.JTextField();
        tfr_charge = new javax.swing.JTextField();
        tfm_charge = new javax.swing.JTextField();
        tfs_charge = new javax.swing.JTextField();
        tfb_discount = new javax.swing.JTextField();
        tft_charge = new javax.swing.JTextField();
        btnb_calculate = new javax.swing.JButton();
        btnb_exite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfbill_discount.setBackground(new java.awt.Color(102, 255, 51));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(255, 0, 204));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("DOCTOR   REGISTRATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );

        jfd_icharge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfd_icharge.setText("Doctor charge");

        jfm_charge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfm_charge.setText("Medicine Charge");

        jfr_charge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfr_charge.setText("Room Charge");

        jfs_charge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_charge.setText("Service Charge");

        jfd_qualification.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfd_qualification.setText("Discount");

        jft_charge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jft_charge.setText("Total Charge");

        tfm_charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfm_chargeActionPerformed(evt);
            }
        });

        btnb_calculate.setBackground(new java.awt.Color(204, 204, 0));
        btnb_calculate.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnb_calculate.setText("calculate");

        btnb_exite.setBackground(new java.awt.Color(204, 204, 0));
        btnb_exite.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnb_exite.setText("EXITE");

        javax.swing.GroupLayout tfbill_discountLayout = new javax.swing.GroupLayout(tfbill_discount);
        tfbill_discount.setLayout(tfbill_discountLayout);
        tfbill_discountLayout.setHorizontalGroup(
            tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tfbill_discountLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfbill_discountLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jfd_icharge)
                                .addComponent(jfm_charge)
                                .addComponent(jfd_qualification)
                                .addComponent(jfr_charge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfs_charge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jft_charge))
                        .addGap(62, 62, 62)
                        .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tfbill_discountLayout.createSequentialGroup()
                                .addComponent(tft_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(tfbill_discountLayout.createSequentialGroup()
                                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfd_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfr_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfm_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfs_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tfb_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tfbill_discountLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnb_calculate)
                        .addGap(197, 197, 197)
                        .addComponent(btnb_exite)
                        .addGap(49, 49, 49))))
        );
        tfbill_discountLayout.setVerticalGroup(
            tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfbill_discountLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfd_icharge)
                    .addComponent(tfd_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfbill_discountLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jfm_charge))
                    .addGroup(tfbill_discountLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tfm_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfr_charge)
                    .addComponent(tfr_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfs_charge)
                    .addComponent(tfs_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfd_qualification)
                    .addComponent(tfb_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jft_charge)
                    .addComponent(tft_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(tfbill_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnb_exite, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnb_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfbill_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfbill_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfm_chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfm_chargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfm_chargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate_bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnb_calculate;
    private javax.swing.JButton btnb_exite;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jfd_icharge;
    private javax.swing.JLabel jfd_qualification;
    private javax.swing.JLabel jfm_charge;
    private javax.swing.JLabel jfr_charge;
    private javax.swing.JLabel jfs_charge;
    private javax.swing.JLabel jft_charge;
    private javax.swing.JTextField tfb_discount;
    private javax.swing.JPanel tfbill_discount;
    private javax.swing.JTextField tfd_charge;
    private javax.swing.JTextField tfm_charge;
    private javax.swing.JTextField tfr_charge;
    private javax.swing.JTextField tfs_charge;
    private javax.swing.JTextField tft_charge;
    // End of variables declaration//GEN-END:variables
}
