/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.managment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Isuranji Thamosha
 */
public final class staff_registration extends javax.swing.JFrame {

    /**
     * Creates new form staff_registration
     * @throws java.sql.SQLException
     */
    public staff_registration() throws SQLException {
        initComponents();
        connect();
        showtabledata();
    }
    
     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
       public void connect()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysQl://localhost:3306/hospital_managment?useSSL=fales","root","Thamo@9812");
           
           }
        catch(ClassNotFoundException | SQLException ex)
        {
            Logger.getLogger(doctor_registration.class.getName()).log(Level.SEVERE,null,ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfs_name = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jfs_id = new javax.swing.JLabel();
        jfs_workingposition = new javax.swing.JLabel();
        jfp_appointdoctorname = new javax.swing.JLabel();
        jfs_adrees = new javax.swing.JLabel();
        jfs_nic = new javax.swing.JLabel();
        jfs_age = new javax.swing.JLabel();
        jfs_contactno = new javax.swing.JLabel();
        jfs_salary = new javax.swing.JLabel();
        txts_id = new javax.swing.JTextField();
        txts_address = new javax.swing.JTextField();
        txts_name = new javax.swing.JTextField();
        txts_nic = new javax.swing.JTextField();
        txts_age = new javax.swing.JTextField();
        txts_contactno = new javax.swing.JTextField();
        txts_salary = new javax.swing.JTextField();
        txts_workingposition = new javax.swing.JTextField();
        btns_insert = new javax.swing.JButton();
        btns_delete = new javax.swing.JButton();
        btns_exite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btns_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfs_name.setBackground(new java.awt.Color(102, 255, 51));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(255, 0, 204));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("STAFF  REGISTRATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );

        jfs_id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_id.setText("Staff ID");

        jfs_workingposition.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_workingposition.setText("Working position");

        jfp_appointdoctorname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfp_appointdoctorname.setText("Staff Name");

        jfs_adrees.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_adrees.setText("Staff Address");

        jfs_nic.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_nic.setText("NIC");

        jfs_age.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_age.setText("Staff Age");

        jfs_contactno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_contactno.setText("Staff contact no");

        jfs_salary.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jfs_salary.setText("Staff Salary");

        txts_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txts_nameActionPerformed(evt);
            }
        });

        txts_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txts_ageActionPerformed(evt);
            }
        });

        txts_contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txts_contactnoActionPerformed(evt);
            }
        });

        btns_insert.setBackground(new java.awt.Color(204, 204, 0));
        btns_insert.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btns_insert.setText("INSERT");
        btns_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_insertActionPerformed(evt);
            }
        });

        btns_delete.setBackground(new java.awt.Color(204, 204, 0));
        btns_delete.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btns_delete.setText("DELETE");
        btns_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_deleteActionPerformed(evt);
            }
        });

        btns_exite.setBackground(new java.awt.Color(204, 204, 0));
        btns_exite.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btns_exite.setText("EXITE");
        btns_exite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_exiteActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Staff ID", "Staff name", "Staff Address", "Staff_nic", "Staff_age", "Staff_contact no", "Staff_salary", "Working_positin"
            }
        ));
        jTable1.setName("jTablestaff"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        btns_update.setBackground(new java.awt.Color(204, 204, 0));
        btns_update.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btns_update.setText("UPDATE");
        btns_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfs_nameLayout = new javax.swing.GroupLayout(tfs_name);
        tfs_name.setLayout(tfs_nameLayout);
        tfs_nameLayout.setHorizontalGroup(
            tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tfs_nameLayout.createSequentialGroup()
                .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfs_id)
                            .addComponent(jfp_appointdoctorname)
                            .addComponent(jfs_workingposition)
                            .addComponent(jfs_salary)
                            .addComponent(jfs_age)
                            .addComponent(jfs_adrees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jfs_nic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jfs_contactno)))
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btns_insert)))
                .addGap(38, 38, 38)
                .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addComponent(btns_delete)
                        .addGap(33, 33, 33)
                        .addComponent(btns_exite, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btns_update, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txts_contactno)
                            .addComponent(txts_salary)
                            .addComponent(txts_workingposition)
                            .addComponent(txts_id, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txts_address, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txts_name, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txts_nic)
                            .addComponent(txts_age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        tfs_nameLayout.setVerticalGroup(
            tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfs_nameLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(298, 298, 298))
                    .addGroup(tfs_nameLayout.createSequentialGroup()
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_id)
                            .addComponent(txts_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfp_appointdoctorname)
                            .addComponent(txts_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_adrees)
                            .addComponent(txts_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_nic)
                            .addComponent(txts_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_age)
                            .addComponent(txts_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_contactno)
                            .addComponent(txts_contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_salary)
                            .addComponent(txts_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfs_workingposition)
                            .addComponent(txts_workingposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tfs_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btns_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btns_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btns_exite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btns_update))
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfs_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfs_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txts_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txts_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txts_nameActionPerformed

    private void txts_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txts_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txts_ageActionPerformed

    private void btns_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_insertActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            String sid=txts_id.getText();
            String sname=txts_name.getText();
            String snic=txts_nic.getText();
            String saddress=txts_address.getText();
            String sage=txts_age.getText();
            String ssalary=txts_salary.getText();
            String sworkingposition=txts_workingposition.getText();
            String scontactno=txts_contactno.getText();
            
            pst=con.prepareStatement("insert into staff_registration(staff_id,staff_name,staff_NIC,staff_address,staff_age,staff_contactNo,staff_salary,working_position)values(?,?,?,?,?,?,?,?)");
            
            pst.setString(1, sid);
            pst.setString(3, sname);
            pst.setString(4, snic);
            pst.setString(5, saddress);
            pst.setString(6, sage);
            pst.setString(7, scontactno);
            pst.setString(8, ssalary);
            pst.setString(9, sworkingposition);
            
            int d=pst.executeUpdate();
            
            if(d==1)
            {
              JOptionPane.showMessageDialog(this,"Recorded Added");
              txts_id.setText("");
               txts_name.setText("");
               txts_nic.setText("");
                txts_address.setText("");
                 txts_salary.setText("");
                  txts_age.setText("");
                   txts_workingposition.setText("");
                     txts_contactno.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"Record insert failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doctor_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            showtabledata();
        } catch (SQLException ex) {
            Logger.getLogger(staff_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btns_insertActionPerformed

    public void showtabledata() throws SQLException
    {
        try{
            String sql="select*from staff_registration";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel1(rs));
            }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
            
    private void btns_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_deleteActionPerformed
        // TODO add your handling code here:
        String sid = txts_id.getText();
        try{
            String sql="DELETE FROM staff_registration where staff_id=?";
            pst=con.prepareStatement(sql);
            pst.setString(1,sid);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record deleted");
            
             txts_id.setText("");
               txts_name.setText("");
               txts_nic.setText("");
                txts_address.setText("");
                 txts_salary.setText("");
                  txts_age.setText("");
                   txts_workingposition.setText("");
                     txts_contactno.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(staff_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btns_deleteActionPerformed

    private void txts_contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txts_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txts_contactnoActionPerformed

    private void btns_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_updateActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            String sid=txts_id.getText();
            String sname=txts_name.getText();
            String saddress=txts_address.getText();
            String snic=txts_nic.getText();
            String sage=txts_age.getText();
            String scontactno=txts_contactno.getText();
            String ssalary=txts_salary.getText();
            String sworkingposition=txts_workingposition.getText();
            
            pst=con.prepareStatement("update staff_registration set staff_name=?, staff_address=?, staff_NIC=?, staff_age=?,patient_contactNo=?, staff_salary=?,working_position=? where staff_id=?");
            
            pst.setString(1, sid);
            pst.setString(2, sname);
            pst.setString(3, saddress);
            pst.setString(4, snic);
            pst.setString(5, sage);
            pst.setString(6, scontactno);
            pst.setString(7, ssalary);
            pst.setString(8, sworkingposition);
            
            int d=pst.executeUpdate();
            
            if(d==1)
            {
              JOptionPane.showMessageDialog(this,"Recored Updated");
              txts_id.setText("");
               txts_name.setText("");
                txts_address.setText("");
                 txts_nic.setText("");
                  txts_age.setText("");
                   txts_contactno.setText("");
                    txts_salary.setText("");
                     txts_workingposition.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"Record update failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doctor_registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btns_updateActionPerformed

    private void btns_exiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_exiteActionPerformed
        // TODO add your handling code here:
        homepage hog=new homepage();
        hog.show();
    }//GEN-LAST:event_btns_exiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new staff_registration().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(staff_registration.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btns_delete;
    private javax.swing.JButton btns_exite;
    private javax.swing.JButton btns_insert;
    private javax.swing.JButton btns_update;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jfp_appointdoctorname;
    private javax.swing.JLabel jfs_adrees;
    private javax.swing.JLabel jfs_age;
    private javax.swing.JLabel jfs_contactno;
    private javax.swing.JLabel jfs_id;
    private javax.swing.JLabel jfs_nic;
    private javax.swing.JLabel jfs_salary;
    private javax.swing.JLabel jfs_workingposition;
    private javax.swing.JPanel tfs_name;
    private javax.swing.JTextField txts_address;
    private javax.swing.JTextField txts_age;
    private javax.swing.JTextField txts_contactno;
    private javax.swing.JTextField txts_id;
    private javax.swing.JTextField txts_name;
    private javax.swing.JTextField txts_nic;
    private javax.swing.JTextField txts_salary;
    private javax.swing.JTextField txts_workingposition;
    // End of variables declaration//GEN-END:variables
}
